{
  description = "XO CE on NixOS - Modular, Xen Orchestra deployment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.05";

    # Xen Orchestra source (pinned to specific commit for stability)
    xoSrc = {
      url = "github:vatesfr/xen-orchestra";
      flake = false;
    };

    # libvhdi source (pinned release for VHD support)
    libvhdiSrc = {
      url = "https://github.com/libyal/libvhdi/releases/download/20240509/libvhdi-alpha-20240509.tar.gz";
      flake = false;
    };
  };

  outputs = { self, nixpkgs, xoSrc, libvhdiSrc, ... }:
  let
    vars = import ./vars.nix;
    system = vars.system;
    pkgs = import nixpkgs { inherit system; };
    lib = nixpkgs.lib;

    # Hardware configuration path (machine-specific, generated by nixos-generate-config)
    hwConfigPath = ./hardware-configuration.nix;
    hwConfigExists = builtins.pathExists hwConfigPath;

    # Minimal config for flake checks (when nixoa.toml/hardware-configuration.nix don't exist)
    checkModeConfig = { config, ... }: {
      # Provide minimal configuration to satisfy NixOS requirements during 'nix flake check'
      # This only activates when hardware-configuration.nix is missing (i.e., in Nix store)
      config = lib.mkIf (!hwConfigExists) {
        # Disable XOA to avoid assertion failures during check
        xoa.enable = lib.mkForce false;

        # Provide minimal filesystem configuration
        fileSystems."/" = {
          device = "/dev/disk/by-label/nixos";
          fsType = "ext4";
        };

        boot.loader.grub.device = "nodev";
      };
    };
  in {
    nixosConfigurations.${vars.hostname} = lib.nixosSystem {
      inherit system;

      modules = [
        # Auto-import all modules from ./modules directory
        ./modules

        # Wire variables into the system
        ({ config, ... }: {
          # Pass variables to all modules
          _module.args.vars = vars;
        })

        # Provide minimal config for flake checks
        checkModeConfig
      ] ++ lib.optionals hwConfigExists [
        # Hardware configuration (only if it exists - allows 'nix flake check' to work)
        hwConfigPath
      ];

      # Provide flake-pinned sources to modules
      specialArgs = { 
        inherit xoSrc libvhdiSrc vars;
      };
    };

    # Runnable helper: nix run .#update-xo
    apps.${system}.update-xo = {
      type = "app";
      program = toString (pkgs.writeShellApplication {
        name = "update-xo";
        runtimeInputs = [ pkgs.jq pkgs.git pkgs.curl ];
        text = ''
          #!/usr/bin/env bash
          set -euo pipefail
          
          echo "🔄 Updating Xen Orchestra source..."
          nix flake lock --update-input xoSrc
          
          echo "📋 Recent commits in xen-orchestra:"
          curl -s https://api.github.com/repos/vatesfr/xen-orchestra/commits?per_page=5 | \
            jq -r '.[] | "  • \(.sha[0:7]) - \(.commit.message | split("\n")[0]) (\(.commit.author.date))"'
          
          echo ""
          echo "✅ Update complete! Review changes with: git diff flake.lock"
          echo "📦 To rebuild: sudo nixos-rebuild switch --flake .#${vars.hostname}"
        '';
      });
      meta = {
        description = "Update the xoSrc input in flake.lock and show new commits.";
      };
    };

    # Development shell
    devShells.${system}.default = pkgs.mkShell {
      packages = with pkgs; [ 
        jq 
        git 
        curl 
        nixos-rebuild
        nix-tree
        nix-diff
      ];
      
      shellHook = ''
        echo "╔══════════════════════════════════════════════════════════╗"
        echo "║           XOA Development Environment                      ║"
        echo "╚══════════════════════════════════════════════════════════╝"
        echo ""
        echo "📋 Available commands:"
        echo "  nix run .#update-xo                    - Update XO source"
        echo "  sudo nixos-rebuild switch --flake .#${vars.hostname} - Deploy changes"
        echo "  sudo nixos-rebuild test --flake .#${vars.hostname}   - Test changes"
        echo "  nix flake check                        - Validate flake"
        echo "  nix flake show                         - Show flake outputs"
        echo ""
        echo "📁 Module locations:"
        echo "  ./modules/system.nix  - Core system configuration"
        echo "  ./modules/xoa.nix     - Xen Orchestra service"
        echo "  ./modules/storage.nix - NFS/CIFS mount support"
        echo "  ./modules/libvhdi.nix - VHD image support"
        echo "  ./modules/extras.nix  - Terminal enhancements"
        echo "  ./vars.nix            - User configuration"
        echo ""
      '';
    };
  };
}
