# SPDX-License-Identifier: Apache-2.0
# NiXOA system override, merged after xo-server's immutable vendor config.

[dataStore]
path = "/var/lib/xo/data"

[http]
redirectToHttps = true

[[http.listen]]
port = 80

[[http.listen]]
cert = "/etc/ssl/xo/certificate.pem"
key = "/etc/ssl/xo/key.pem"
port = 443

[http.mounts]
"/" = "/var/lib/xo/xen-orchestra/@xen-orchestra/web/dist"
"/v5" = "/var/lib/xo/xen-orchestra/packages/xo-web/dist"
"/v6" = "/var/lib/xo/xen-orchestra/@xen-orchestra/web/dist"

[redis]
socket = "/run/redis-xo/redis.sock"

[remoteOptions]
mountsDir = "/var/lib/xo/mounts"
useSudo = true

[tempDir]
path = "/var/lib/xo/tmp"
