# SPDX-License-Identifier: Apache-2.0
# Generated by maestro-menu. Hand-edited settings belong in settings.nix.
{...}: {
  maestro.operator.menu = {
    extraSystemPackages = [];
    extraUserPackages = [];
    enabledServices = [];
  };
}
